config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_one_attached :image

    validates :full_name, presence: true
    validates :phone_number, presence: true    
    validates :notes, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    # Controller actions and methods
    def index
        @customers = Customer.all
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<!-- app/views/customers/_customer.html.erb -->

<div class="customer-card">
<%= stylesheet_link_tag 'customers', media: 'all', 'data-turbolinks-track': 'reload' %>


  <div class="customer-info">
    <% if customer.image.attached? %>
      <%= image_tag url_for(customer.image), class: "customer-image" %>
    <% else %>
      <span class="customer-placeholder-image">No image available</span>
    <% end %>

    <h3 class="customer-name"><%= customer.full_name %></h3>
    <p class="customer-phone"><%= customer.phone_number %></p>
    <p class="customer-email"><%= customer.email_address %></p>
    <p class="customer-notes"><%= customer.notes %></p>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<h1>Alphabetized Customers</h1>

<!-- Back to index view -->
<%= link_to 'Back to All Customers', customers_path, class: 'nice-link' %>

<div class="customer-cards">
  <% @customers.each do |customer| %>
    <%= render partial: 'customer', locals: { customer: customer } %>
  <% end %>
</div>

app/views/customers/index.html.erb
<!-- app/views/customers/index.html.erb -->

<h1>All Customers</h1>
<div class="customer-cards">
  <% @customers.each do |customer| %>
    <div class="customer-card">
      <%= render partial: 'customer', locals: { customer: customer } %>
    </div>
  <% end %>
</div>

app/views/customers/missing_email.html.erb
<!-- app/views/customers/missing_email.html.erb -->
<h1>Customers with Missing Email</h1>

<!-- Back to index view -->
<%= link_to 'Back to All Customers', customers_path, class: 'nice-link' %>

<div class="customer-cards">
  <% @customers.each do |customer| %>
  <div class="customer-card">
    <%= render partial: 'customer', locals: { customer: customer } %>
  </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>